name: "Infrastructure" 

pool:
  vmImage: windows-latest

variables:
  - group: Infrastructure

trigger: none

jobs:
  - job: Deploy
    steps:
      - powershell: ../bin/terraform.exe init
        displayName: "Terraform init"
        workingDirectory: $(Build.SourcesDirectory)/terraform/infrastructure
        failOnStderr: true
        env:
          ARM_SUBSCRIPTION_ID: $(Subscription_Id)
          ARM_CLIENT_ID: $(Client_Id)
          ARM_CLIENT_SECRET: $(Client_Secret)
          ARM_TENANT_ID: $(Tenant_Id)
          TF_VAR_Agent_Name: $(Build_Agent_SPN_Name)

      - powershell: ../bin/terraform.exe destroy -auto-approve
        displayName: "Destroy plan"
        workingDirectory: $(Build.SourcesDirectory)/terraform/infrastructure
        failOnStderr: true
        env:
          ARM_SUBSCRIPTION_ID: $(Subscription_Id)
          ARM_CLIENT_ID: $(Client_Id)
          ARM_CLIENT_SECRET: $(Client_Secret)
          ARM_TENANT_ID: $(Tenant_Id)
          TF_VAR_Agent_Name: $(Build_Agent_SPN_Name)